name: Test

on: push

jobs:
  sentinel-test:
    runs-on: 'ubuntu-latest'
    steps:
      - run: | 
          wget https://releases.hashicorp.com/sentinel/0.27.0/sentinel_0.27.0_linux_386.zip
          unzip sentinel_0.27.0_linux_386.zip
          rm sentinel_0.27.0_linux_386.zip
          sudo mv sentinel /usr/local/bin
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sentinel test
